server:
  port: 8895
  servlet:
    context-path: /


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dreamcloud?serverTimezone=UTC
    username: root
    password: 365487740
thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  cache: false
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static

mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.lhy.**.entity
  configuration:
    auto-mapping-behavior: full

logging:
  level:
    com:
      shop:
        miniso:
          dao: debug